FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/proxy ./cmd/proxy

FROM gcr.io/distroless/base-debian12
COPY --from=build /bin/proxy /proxy
EXPOSE 8080
ENTRYPOINT ["/proxy"]
